### PR TITLE
Fix modeling page 304

### LINKED ISSUE #2654: 304 on /models
When I try to navigate or load `/models` directly I'm getting a 304 and a blank page.

image

It looks like this is an issue that is fixed in the [14.0.2 patch release](https://github.com/vercel/next.js/releases/tag/v14.0.2), but there may be other workarounds: https://github.com/vercel/next.js/issues/56018

### PR DESCRIPTION
**Pull request by abkfenris**
Updates Next to hopefully fix modeling page 304. The modeling page also didn't include the openlayers CSS, so on a fresh load the map would be unstyled.

Closes #2654

### CODE REVIEW

**Comment by abkfenris** [comment]
@Adelle-Pitsas Weren't you wrangling document access during the build of the model pages? Did it look like this? https://github.com/gulfofmaine/Neracoos-1-Buoy-App/actions/runs/6818389927/job/18543915098?pr=2655#step:8:27

**Comment by Adelle-Pitsas** [comment]
> @Adelle-Pitsas Weren't you wrangling document access during the build of the model pages? Did it look like this? https://github.com/gulfofmaine/Neracoos-1-Buoy-App/actions/runs/6818389927/job/18543915098?pr=2655#step:8:27

Yeah, thats what it looked like. Hmmm it was building those static pages fine yesterday.

**Comment by abkfenris** [comment]
Ya, it seems like there might have been some change with Next 14.0.2 that's making the build cranky.

**Comment by abkfenris** [comment]
Possibly an issue with the Highcharts ModelChart https://github.com/vercel/next.js/issues/58379

**Comment by abkfenris** [comment]
Oh, and now the build fails?

**Review by Adelle-Pitsas — APPROVED** [review]

**Comment by Adelle-Pitsas** [comment]
Nice! Looking good.

**Pull request merged**
