### PR TITLE
Add icons for external links and current conditions

### LINKED ISSUE #1112: Add icons to show plots can expand and to indicate outbound links
- Add an expand icon to the Latest Condition plots to indicate that they can be enlarged
[https://fontawesome.com/icons/expand-alt?style=solid](https://fontawesome.com/icons/expand-alt?style=solid)

- Add an outbound link icon to More Info links
[https://fontawesome.com/icons/external-link-alt?style=solid](https://fontawesome.com/icons/external-link-alt?style=solid)

### PR DESCRIPTION
**Pull request by abkfenris**
@youngmorse @tshyka 

How does this look for external links?
image

And having the icon in the bottom right?

image

Closes #1112

### CODE REVIEW

**Comment by youngmorse** [comment]
I think external links icon looks really good. The expand looks like it's floating a bit in all the white space. I can see where that would have been hard to make fit on the top row especially for the data types with the long names. I think it makes the point that the plot is clickable. 

 I wonder if the [four arrows](https://fontawesome.com/icons/expand-arrows-alt?style=solid) or the [expanded square](https://fontawesome.com/icons/expand?style=solid) might work a little better given the location? 
Screen Shot 2021-03-08 at 5 02 21 PM
Screen Shot 2021-03-08 at 5 02 18 PM

**Comment by abkfenris** [comment]
`faExpand`

image

`faExpandArrowsAlt`

image

**Review by youngmorse — APPROVED** [review]

**Comment by tshyka** [comment]
Those look good to me.

**Comment by abkfenris** [comment]
Going with the square expanders `faExpand`.

**Comment by abkfenris** [comment]
Released with [v0.6.7](https://github.com/gulfofmaine/Neracoos-1-Buoy-App/releases/tag/v0.6.7)

**Pull request merged**
